### ISSUE TITLE
pix.py doesn't convert the image properly

### ISSUE THREAD

**Issue by marvk** [yuri91/placebot#1]
Using [this ](http://i.imgur.com/UhfpjDn.png) image, I get the following output with

`py pix.py .\img.png --location 456 863`

`{"pixels": [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], "size": [23, 7], "location": [456, 863]}`

**Comment by lawnmowerlatte** [comment]
A moot point, but I think your picture has colors that don't match the available pallet. I had this happen despite it being a picture of r/place, the colors weren't an exact match.
